[package]
name = "araf-aljami-me"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1"
markdown = "1.0.0"
fs_extra = "1.3.0"
glob = "0.3.2"
toml = "0.8.23"
