# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr: none
trigger:
- master

pool:
  default

jobs:
- job: Build
  steps:
  - template: templates/build.yml
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  - task: Docker@2
    inputs:
      containerRegistry: 'ajami1331.azurecr.io'
      command: 'login'
  - task: Docker@2
    inputs:
      containerRegistry: 'ajami1331.azurecr.io'
      repository: 'araf.aljami.me'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'docker-compose.yml'
      TargetFolder: $(Build.ArtifactStagingDirectory)/docker-compose
  - upload: $(Build.ArtifactStagingDirectory)/docker-compose
    artifact: docker-compose

- deployment: VMDeploy
  dependsOn: Build
  displayName: web
  environment:
    name: prod
    resourceType: VirtualMachine
    tags: web
  strategy:
    rolling:
      maxParallel: 100%
      preDeploy:
        steps:
          - download: current
            artifact: build
          - download: current
            artifact: docker-compose
          - script: echo downloaded built artifact
      deploy:
        steps:
          - script: |
              set -e
              rm -rf ~/araf.aljami.me/
              cp -r $(Pipeline.Workspace)/build ~/araf.aljami.me/
              sudo service nginx restart
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          - task: Docker@2
            inputs:
              containerRegistry: 'ajami1331.azurecr.io'
              command: 'login'
          - script: |
              cd $(Pipeline.Workspace)/docker-compose
              docker compose up -d

      routeTraffic:
          steps:
          - script: echo routing traffic
      postRouteTraffic:
          steps:
          - script: echo health check post-route traffic
      on:
        failure:
          steps:
          - script: echo Restore from backup! This is on failure
        success:
          steps:
          - script: echo Notify! This is on success