pr: none
trigger:
- master

pool: 
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'ajami1331.azurecr.io'
      repository: 'araf.aljami.me'
      command: 'buildAndPush'
      tags: |
        $(Build.BuildId)
        latest
      Dockerfile: '**/Dockerfile'
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Visual Studio Enterprise Subscription(fd24d692-fa14-4ae1-bc9c-b6bd3c64d6d0)'
      azureContainerRegistry: '{"loginServer":"ajami1331.azurecr.io", "id" : "/subscriptions/fd24d692-fa14-4ae1-bc9c-b6bd3c64d6d0/resourceGroups/araf-build-agents/providers/Microsoft.ContainerRegistry/registries/ajami1331"}'
      dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
      projectName: 
      action: 'Lock services'
      outputDockerComposeFile: '$(Build.StagingDirectory)/docker-compose.yml'
  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
      SourceFolder: '$(Build.StagingDirectory)'
      Contents: 'docker-compose.yml'
      TargetFolder: $(Build.ArtifactStagingDirectory)/docker-compose
  - upload: $(Build.ArtifactStagingDirectory)/docker-compose
    artifact: docker-compose
