pr:
- master
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'ajami1331.azurecr.io'
      command: 'build'
      Dockerfile: '**/Dockerfile'