pr:
- master
trigger: none

pool:
  default

jobs:
- job: Build
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'ajami1331.azurecr.io'
      repository: 'araf.aljami.me'
      command: 'build'
      tags: |
        $(Build.BuildId)
        latest
      Dockerfile: '**/Dockerfile'